title: Songyan Lai's Homepage
page-top-title: Songyan Lai
top-section-bg-text: Computer Science
home-subtitle: Songyan Lai&ensp;|&ensp;赖松岩
copyright-text: "&copy; Songyan Lai 2025. All Rights Reserved."
